-- Run this in Supabase SQL Editor to create auth table + seed accounts.
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  username VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL CHECK (role IN ('admin', 'student')),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE OR REPLACE FUNCTION public.set_users_updated_at() RETURNS TRIGGER AS $$ BEGIN NEW.updated_at = NOW();
RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS trg_users_updated_at ON public.users;
CREATE TRIGGER trg_users_updated_at BEFORE
UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.set_users_updated_at();

CREATE TABLE IF NOT EXISTS public.violations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category VARCHAR(50) NOT NULL, -- 'Minor Offenses', 'Major Offenses'
  degree VARCHAR(50) NOT NULL, -- 'First Degree', 'Second Degree', etc.
  name VARCHAR(255) NOT NULL,
  parent_id BIGINT REFERENCES public.violations(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE OR REPLACE FUNCTION public.set_violations_updated_at() RETURNS TRIGGER AS $$ BEGIN NEW.updated_at = NOW();
RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS trg_violations_updated_at ON public.violations;
CREATE TRIGGER trg_violations_updated_at BEFORE
UPDATE ON public.violations FOR EACH ROW EXECUTE FUNCTION public.set_violations_updated_at();

-- Seed violations data
INSERT INTO public.violations (category, degree, name, parent_id) VALUES
-- Minor Offenses - First Degree
('Minor Offenses', 'First Degree', 'Loitering', NULL),
('Minor Offenses', 'First Degree', 'Littering', NULL),
('Minor Offenses', 'First Degree', 'Classroom Disturbance', NULL),
('Minor Offenses', 'First Degree', 'Eating/Drinking in Academic Facilities', NULL),
('Minor Offenses', 'First Degree', 'Improper disposal of waste/littering', NULL),
('Minor Offenses', 'First Degree', 'Not wearing a school ID', NULL),
('Minor Offenses', 'First Degree', 'Unauthorized use of school property', NULL),
('Minor Offenses', 'First Degree', 'Inappropriate Attire', NULL),
('Minor Offenses', 'First Degree', 'Shorts, skirts, or dresses that are above mid-thigh or excessively short', (SELECT id FROM public.violations WHERE name = 'Inappropriate Attire')),
('Minor Offenses', 'First Degree', 'Low-rise, tattered, or ripped jeans', (SELECT id FROM public.violations WHERE name = 'Inappropriate Attire')),
('Minor Offenses', 'First Degree', 'Lounge wear, pajamas, leggings worn as outwear', (SELECT id FROM public.violations WHERE name = 'Inappropriate Attire')),
('Minor Offenses', 'First Degree', 'Sleeveless tops, tube tops, plunging necklines, or low-cut shirts', (SELECT id FROM public.violations WHERE name = 'Inappropriate Attire')),
('Minor Offenses', 'First Degree', 'Midriff-exposing tops or see-through garments', (SELECT id FROM public.violations WHERE name = 'Inappropriate Attire')),
('Minor Offenses', 'First Degree', 'Shirts or blouses that promote alcohol, tobacco, hatred, drugs, any illegal act, or offensive content', (SELECT id FROM public.violations WHERE name = 'Inappropriate Attire')),
('Minor Offenses', 'First Degree', 'Unnaturally bright or extreme hair colors', (SELECT id FROM public.violations WHERE name = 'Inappropriate Attire')),
('Minor Offenses', 'First Degree', 'Wearing multiple or oversized accessories', (SELECT id FROM public.violations WHERE name = 'Inappropriate Attire')),
('Minor Offenses', 'First Degree', 'Slippers, flip-flops', (SELECT id FROM public.violations WHERE name = 'Inappropriate Attire')),
('Minor Offenses', 'First Degree', 'Slip-on clogs with open backs, excessive holes', (SELECT id FROM public.violations WHERE name = 'Inappropriate Attire')),
('Minor Offenses', 'First Degree', 'Open-toe and strappy sandals', (SELECT id FROM public.violations WHERE name = 'Inappropriate Attire')),
('Minor Offenses', 'First Degree', 'Step-ins or slip-on shoes without heel supports', (SELECT id FROM public.violations WHERE name = 'Inappropriate Attire')),
('Minor Offenses', 'First Degree', 'Sitting on the stairs', NULL),

-- Minor Offenses - Second Degree
('Minor Offenses', 'Second Degree', 'Courting/Coupling', NULL),
('Minor Offenses', 'Second Degree', 'PDA', (SELECT id FROM public.violations WHERE name = 'Courting/Coupling')),
('Minor Offenses', 'Second Degree', 'Holding or Touching', (SELECT id FROM public.violations WHERE name = 'Courting/Coupling')),
('Minor Offenses', 'Second Degree', 'Rough games / Quarreling / Boisterous behavior', NULL),
('Minor Offenses', 'Second Degree', 'Use of Vulgar Expressions', NULL),
('Minor Offenses', 'Second Degree', 'Unauthorized use of gadgets within class hours', NULL),
('Minor Offenses', 'Second Degree', 'Cutting classes', NULL),

-- Major Offenses - Third Degree
('Major Offenses', 'Third Degree', 'Lending or using somebody else''s ID', NULL),
('Major Offenses', 'Third Degree', 'Insubordination', NULL),
('Major Offenses', 'Third Degree', 'Vandalism', NULL),
('Major Offenses', 'Third Degree', 'Pornographic Materials / Obscenity', NULL),
('Major Offenses', 'Third Degree', 'Disrespect to Authority', NULL),
('Major Offenses', 'Third Degree', 'Unauthorized Use of School Name/Representation', NULL),
('Major Offenses', 'Third Degree', 'Cat calling / name calling', NULL),

-- Major Offenses - Fourth Degree
('Major Offenses', 'Fourth Degree', 'Cheating', NULL),
('Major Offenses', 'Fourth Degree', 'Stealing', NULL),

-- Major Offenses - Fifth Degree
('Major Offenses', 'Fifth Degree', 'Possession or Passing of Fireworks', NULL),
('Major Offenses', 'Fifth Degree', 'Improper behavior', NULL),
('Major Offenses', 'Fifth Degree', 'Bribery', (SELECT id FROM public.violations WHERE name = 'Improper behavior')),
('Major Offenses', 'Fifth Degree', 'Theft', (SELECT id FROM public.violations WHERE name = 'Improper behavior')),
('Major Offenses', 'Fifth Degree', 'Extortion', (SELECT id FROM public.violations WHERE name = 'Improper behavior')),
('Major Offenses', 'Fifth Degree', 'Acts of Violence', (SELECT id FROM public.violations WHERE name = 'Improper behavior')),
('Major Offenses', 'Fifth Degree', 'Falsification', (SELECT id FROM public.violations WHERE name = 'Improper behavior')),
('Major Offenses', 'Fifth Degree', 'Deceitful acts', (SELECT id FROM public.violations WHERE name = 'Improper behavior')),
('Major Offenses', 'Fifth Degree', 'Slander', (SELECT id FROM public.violations WHERE name = 'Improper behavior')),
('Major Offenses', 'Fifth Degree', 'Gambling', (SELECT id FROM public.violations WHERE name = 'Improper behavior')),
('Major Offenses', 'Fifth Degree', 'Violence', NULL),
('Major Offenses', 'Fifth Degree', 'Fist fighting', (SELECT id FROM public.violations WHERE name = 'Violence')),
('Major Offenses', 'Fifth Degree', 'Physical injury', (SELECT id FROM public.violations WHERE name = 'Violence')),
('Major Offenses', 'Fifth Degree', 'Choking', (SELECT id FROM public.violations WHERE name = 'Violence')),
('Major Offenses', 'Fifth Degree', 'Threatening', (SELECT id FROM public.violations WHERE name = 'Violence')),
('Major Offenses', 'Fifth Degree', 'Intimidating others', (SELECT id FROM public.violations WHERE name = 'Violence')),
('Major Offenses', 'Fifth Degree', 'Bullying', NULL),
('Major Offenses', 'Fifth Degree', 'Written or Action', (SELECT id FROM public.violations WHERE name = 'Bullying')),
('Major Offenses', 'Fifth Degree', 'Possession or Passing of Deadly Weapons', NULL),
('Major Offenses', 'Fifth Degree', 'Alcohol', NULL),
('Major Offenses', 'Fifth Degree', 'Bringing or drinking alcoholic beverages', (SELECT id FROM public.violations WHERE name = 'Alcohol')),
('Major Offenses', 'Fifth Degree', 'Coming to school intoxicated or under the influence of alcohol', NULL),
('Major Offenses', 'Fifth Degree', 'Smoking or Vaping', NULL),

-- Major Offenses - Sixth Degree
('Major Offenses', 'Sixth Degree', 'Any act of dishonesty', NULL),
('Major Offenses', 'Sixth Degree', 'Defamation', NULL),
('Major Offenses', 'Sixth Degree', 'Immoralities', NULL),
('Major Offenses', 'Sixth Degree', 'Sexual Harassment', NULL),
('Major Offenses', 'Sixth Degree', 'Malicious acts', NULL),

-- Major Offenses - Seventh Degree
('Major Offenses', 'Seventh Degree', 'Unrecognized Organizations', NULL),
('Major Offenses', 'Seventh Degree', 'Drug Possession/Distribution', NULL),
('Major Offenses', 'Seventh Degree', 'Acts of Harm', NULL),
('Major Offenses', 'Seventh Degree', 'Explosives', NULL),
('Major Offenses', 'Seventh Degree', 'Unauthorized Strikes', NULL),
('Major Offenses', 'Seventh Degree', 'Dishonor to PLP', NULL),
('Major Offenses', 'Seventh Degree', 'Public Misconduct', NULL),
('Major Offenses', 'Seventh Degree', 'Defamatory/Obscene Content', NULL),
('Major Offenses', 'Seventh Degree', 'Vandalism', NULL),
('Major Offenses', 'Seventh Degree', 'Unauthorized Representation', NULL),
('Major Offenses', 'Seventh Degree', 'Unauthorized Media Statements', NULL),
('Major Offenses', 'Seventh Degree', 'Event Disruption', NULL)
ON CONFLICT DO NOTHING;

INSERT INTO public.users (email, username, password_hash, role, is_active)
VALUES (
    'jennypatanag@gmail.com',
    'jen25',
    '$2b$12$waYZbff4Hba7QUsWdYP7l.iPL.BOkAgJwOM732EtHB4CbD3ed8vsC',
    'admin',
    TRUE
  ),
  (
    'hermoso_lyrika@plpasig.edu.ph',
    'leeRiKang',
    '$2b$12$JBRsGLGl3Ym4YgWXvM.mguzweGLw7/m0GgAYCU6IjxE1vcYrCOy.6',
    'student',
    TRUE
  ) ON CONFLICT (username) DO
UPDATE
SET email = EXCLUDED.email,
  password_hash = EXCLUDED.password_hash,
  role = EXCLUDED.role,
  is_active = TRUE;
SELECT id,
  email,
  username,
  role,
  is_active,
  created_at,
  updated_at
FROM public.users
ORDER BY id;